services:
  app:
    build: .
    user: node
    container_name: nestjs-typeorm-app
    entrypoint: docker-entrypoint.sh
    privileged: true
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app
    depends_on:
      - db
    networks:
      - api-network
    command: "/usr/app/docker-entrypoint.sh"

  db:
    build: .docker/postgres
    container_name: nestjs-typeorm-db
    restart: always
    tty: true
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
